name: Build and Push Docker Images

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: distccd-aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: docker/setup-buildx-action@v3
        name: Setup Buildx
      - uses: docker/login-action@v3
        name: Login GHCR
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v5   
        name: Build and push Docker images         
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
